version: '3'
services:
  redis:
    container_name: redis
    image: redis:3.2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config:/usr/local/etc/redis
  netcat:
    build: netcat/.
    command: qwe
    ports:
      - '8080:8080'
    volumes:
    - ./log:/var/log
  app_1:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' --pid tmp/pids/server_1.pid
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - netcat
  app_2:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' --pid tmp/pids/server_2.pid
    volumes:
      - .:/app
    ports:
      - '3001:3000'
    depends_on:
      - redis
      - netcat
  app_3:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' --pid tmp/pids/server_3.pid
    volumes:
      - .:/app
    ports:
      - '3002:3000'
    depends_on:
      - redis
      - netcat
  sidekiq:
    build: .
    command: bundle exec sidekiq -q default
    depends_on:
      - redis
    volumes:
      - .:/app
